function Level1(){
	var jsonData = {
				"rows":{
					"1":{
						"columns":{
							"1":{
								"type":"Type1",
								"color:":"random",
								"position":"random"
							},
							"2":{
								"type":"Type3",
								"color:":"random",
								"position":"random"
							},
							"3":{
								"type":"Type4",
								"color:":"random",
								"position":"random"
							},
							"4":{
								"type":"Type5",
								"color:":"random",
								"position":"random"
							},
							"5":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"6":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"7":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							}
						}
					},
					"2":{
						"columns":{
							"1":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"2":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"3":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"4":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"5":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"6":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"7":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							}
						}
					},
					"3":{
						"columns":{
							"1":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"2":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"3":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"4":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"5":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"6":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"7":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							}
						}
					},
					"4":{
						"columns":{
							"1":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"2":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"3":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"4":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"5":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"6":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"7":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							}
						}
					},
					"5":{
						"columns":{
							"1":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"2":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"3":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"4":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"5":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"6":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"7":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							}
						}
					},
					"6":{
						"columns":{
							"1":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"2":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"3":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"4":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"5":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"6":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"7":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							}
						}
					},
					"7":{
						"columns":{
							"1":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"2":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"3":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"4":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"5":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"6":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							},
							"7":{
								"type":"Type2",
								"color:":"random",
								"position":"random"
							}
						}					
					}
				}
			}

	this.grid = jsonData;
}